const fs=require("fs");
const p="C:/Users/Owner/agency/clients/ga-tucker-pi/seo-audit-2026-07-02/geo.md";
const L=[];
L.push("# GEO / AI-Search Audit - G.A. Tucker PI");
L.push("_Audit date: 2026-07-02 | Auditor: GEO Specialist | Pages assessed: /, /about, /background-checks, /investigations, /infidelity_");
L.push("");
L.push("---");
L.push("");
L.push("## Overall AI-Readiness Score: 42 / 100");
L.push("");
L.push("| Dimension | Weight | Raw Score | Weighted |");
L.push("|-----------|--------|-----------|----------|");
L.push("| Citability | 25% | 38/100 | 9.5 |");
L.push("| Structural Readability | 20% | 45/100 | 9.0 |");
L.push("| Multi-Modal Content | 15% | 40/100 | 6.0 |");
L.push("| Authority and Brand Signals | 20% | 48/100 | 9.6 |");
L.push("| Technical Accessibility | 20% | 80/100 | 16.0 |");
L.push("| **TOTAL** | | | **42 (penalized for FAQ shell issue)** |");
L.push("");
L.push("> Penalty applied: FAQ questions present on /background-checks and /infidelity with no rendered answer text. AI crawlers extract empty answers, which actively hurts citability and schema value.");
L.push("");
L.push("---");
L.push("");
L.push("## AI Crawler Access Status");
L.push("");
L.push("| Crawler | Status in robots.txt |");
L.push("|---------|----------------------|");
L.push("| GPTBot | Allowed |");
L.push("| OAI-SearchBot (ChatGPT-User) | Allowed |");
L.push("| ClaudeBot / Claude-Web | Allowed |");
L.push("| anthropic-ai | Allowed |");
L.push("| Google-Extended (Google AIO) | Allowed |");
L.push("| PerplexityBot | Not explicitly listed; no Disallow - crawlable by default |");
L.push("| CCBot | Not blocked (training crawler; low priority concern for PI site) |");
L.push("");
L.push("**Verdict: Access is strong. No crawler is locked out. This is the site's single biggest GEO asset.**");
L.push("");
L.push("---");
L.push("");
L.push("## llms.txt Status");
L.push("");
L.push("**Present: YES**");
L.push("");
L.push("The file exists at https://gatuckerpi.com/llms.txt and is populated with substantive content.");
L.push("");
L.push("**Positives:**");
L.push("- Business name, owner, license number (PI188351), and phone number are present");
L.push("- Service list is complete (9 categories)");
L.push("- Hourly rate ($211/hr) is explicitly stated - a rare, highly citable data point");
L.push("- Service territory (5 Southern California counties) is enumerated");
L.push("- Professional credentials (3 master degrees, affiliations) are declared");
L.push("");
L.push("**Gaps:**");
L.push("- No RSL 1.0 licensing declaration (AI training permission/restriction signal missing)");
L.push("- No structured Pages section linking to individual service URLs");
L.push("- No FAQ block or structured Q&A content");
L.push("- City (Murrieta, CA) is absent - the file references Southern California only");
L.push("- No Last-Updated timestamp");
L.push("");
L.push("**llms.txt Score: 58/100** - file exists and has real data, but lacks the canonical URL listing, licensing signal, and city-level precision that maximize AI model use.");
L.push("");
L.push("---");
L.push("");
L.push("## Dimension Breakdown");
L.push("");
L.push("### 1. Citability (38/100)");
L.push("");
L.push("The site has a few genuinely citable facts but is dominated by marketing language that AI models cannot quote as authoritative.");
L.push("");
L.push("**Citable assets found:**");
L.push("- Under the Fair Credit Reporting Act (FCRA), criminal background checks cannot contain records of civil suits or arrests after seven years. Source: /background-checks. Strong, attributable legal fact.");
L.push("- Criminal convictions remain on record indefinitely in California. Source: /background-checks. Citable California-specific claim.");
L.push("- California PI License #PI188351 - appears on every page; consistent named-entity anchor");
L.push("- $211/hour for ongoing services (llms.txt) - specific pricing data AI models can cite");
L.push("- 27+ years of investigative experience (/about) - quantified credential");
L.push("");
L.push("**Non-citable patterns dominating the copy:**");
L.push("- discreet, professional investigations to uncover the truth - generic, unquotable");
L.push("- decades of combined experience (/investigations, /infidelity) - vague vs. the 27+ stated on /about");
L.push("- advanced surveillance techniques, digital forensics - no process specifics");
L.push("- /investigations has zero California law references and zero procedural specifics");
L.push("- /infidelity has zero statistics and no concrete timelines");
L.push("");
L.push("**Critical gap:** Optimal AI-citation passages run 134-167 words and open with a direct answer. No page on this site has a passage conforming to that pattern. Most sections open with marketing positioning, not factual statements.");
L.push("");
L.push("---");
L.push("");
L.push("### 2. Structural Readability (45/100)");
L.push("");
L.push("**Positives:**");
L.push("- /background-checks has the strongest heading hierarchy - logical H1 to H2 to H3 nesting");
L.push("- FAQ section headings exist on /background-checks and /infidelity");
L.push("- /about has clean named-entity structure (separate sections for Greg and Julia)");
L.push("");
L.push("**Problems:**");
L.push("- Homepage H1 is HIRE CALIFORNIAS LEADING PRIVATE INVESTIGATOR - a marketing claim. AI models prefer H1s that name the entity + service + location");
L.push("- /investigations H1 is Investigation Services - zero location signal, zero differentiation");
L.push("- /infidelity H1 is Infidelity Investigations - same problem");
L.push("- FAQ questions on /background-checks and /infidelity have NO visible answer text. Most damaging structural failure: the page signals Q&A content exists, then delivers nothing extractable");
L.push("- No question-format H2/H3 headings outside the broken FAQ blocks");
L.push("- Inconsistent business name across pages: G.A. Tucker P.I. Investigative Services L.L.C vs. GA Tucker PI Investigative Services LLC vs. G.A. Tucker PI - entity disambiguation fails");
L.push("");
